
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

tuya_smart_ir_ac:
  access_id: "3kc739q8f8umehepaths"
  access_secret: "3c88e136fedd40918fedd47121befbd8"
  country: "US"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
