services:
  web:
    build: .
    container_name: ozzulab-sqli-ho30-web
    restart: unless-stopped
    networks: { labnet: { ipv4_address: 10.10.35.20 } }
networks:
  labnet:
    ipam: { config: [ { subnet: 10.10.35.0/24 } ] }
