server {
    listen 80 default_server;
    server_name edge-gw.skyline.local _;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Old "status" endpoint left exposed — recon breadcrumb
    location = /status {
        return 200 "edge-gw OK\nhostname: edge-gw.skyline.local\ninternal_portal: http://internal-web.skyline.local/\n";
        add_header Content-Type text/plain;
    }
}
