apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'expo.modules.pcmplayer'
version = '0.1.0'

android {
  namespace "expo.modules.pcmplayer"
  compileSdkVersion safeExtGet("compileSdkVersion", 34)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 29)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation project(':expo-modules-core')
}

int safeExtGet(String prop, Integer fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
