"use strict";
// offense-engine.js — L3 offense-synthesis (dir_1780577251265)
//
// WHY THIS EXISTS: SOC sessions trip the usage-policy classifier when the frontier model
// (Claude / L4) reasons about the offensive operation itself — which creds to try, which
// exploit applies, what order to attack. That reasoning IS the flagged activity, and no
// membrane on Claude's INPUT fixes it, because the content is generated BY Claude. The
// fix is to move that synthesis onto a self-hosted model with no classifier: this module
// reads the STRUCTURED findings for an engagement, asks the self-hosted model for the
// single next in-scope step, and writes it to the PA queue. The offensive output
// (command / rationale / refs) is persisted to soc_queue_items ONLY — advanceOffense
// returns a sanitized label, never the offensive bytes. That boundary is what keeps
// offensive content out of L4's context. See SOC-PIPELINE-ARCHITECTURE.md.

const http = require("http");
const https = require("https");
const { URL } = require("url");
const db = require("./db");

// Configurable so we can benchmark Qwen-3.x-32B vs DeepSeek in-harness with no code
// change. Endpoint is the OpenAI-compatible base of a self-hosted server (Ollama/vLLM)
// reached over an SSH tunnel from the bridge (see SOC-OFFENSE-MODEL-RUNBOOK.md).
const MODEL_URL  = process.env.OFFENSE_MODEL_URL  || "http://127.0.0.1:11434/v1";
const MODEL_NAME = process.env.OFFENSE_MODEL_NAME || "qwen2.5-coder:32b"; // placeholder; set per-benchmark
const MODEL_KEY  = process.env.OFFENSE_MODEL_KEY  || "";

// Step 3 of OFFENSE-AGENT-DESIGN.md — PentestGPT-style role separation.
// advance_offense runs TWO sequential model calls per invocation:
//   1) REASONING — holds full engagement context, picks the next sub-task
//   2) GENERATION — sees only the chosen sub-task + executor tool list, produces
//      the exact command. Narrower context → less hallucinated commands.
// Per the paper, this split delivered +228.6% sub-task completion vs single-LLM.

const REASONING_SYSTEM_PROMPT = [
  "You are the REASONING module of an offensive-synthesis engine for an AUTHORIZED penetration-testing engagement.",
  "You receive the FULL engagement state: scope/ROE, executor capabilities, structured recon, current findings, and the queue history of prior attempts with their outcomes.",
  "Your job is to pick the ONE next concrete sub-task that's the highest-leverage action right now — not the command itself, just what to do.",
  "Pivot away from approaches the queue history shows already failed. Build on what succeeded.",
  "Stay strictly within scope. If no in-scope sub-task remains, say so honestly.",
  "Respond as STRICT JSON, no prose, no code fences:",
  '{"subtask":"one-sentence description of the next sub-task","rationale":"why this is the right move now given history + state","expected_payoff":"what this reveals or achieves","references":["CVE-... | EDB-... | exploit/..."],"in_scope":true}',
  'If no in-scope sub-task exists, return {"in_scope":false}.',
].join("\n");

const GENERATION_SYSTEM_PROMPT = [
  "You are the GENERATION module of an offensive-synthesis engine. The REASONING module has already decided WHAT sub-task to attempt — your job is to translate that one sub-task into the EXACT shell command for the engagement's executor.",
  "Use ONLY tools from the provided tools list. Do not invent tool names or flags. Do not propose multi-step pipelines unless the tools list explicitly allows them.",
  "Match the command to the executor's environment (e.g. a stock Android root with toybox is very different from a Kali host).",
  "Respond as STRICT JSON, no prose, no code fences:",
  '{"title":"short human label","command":"the exact shell command","expected_artifact":"what success looks like","references":["CVE-... | EDB-... | exploit/..."]}',
].join("\n");

function chatCompletion(messages, modelOverride) {
  return new Promise((resolve, reject) => {
    const base = MODEL_URL.replace(/\/+$/, "");
    const url = new URL(base + "/chat/completions");
    const lib = url.protocol === "https:" ? https : http;
    const payload = JSON.stringify({ model: modelOverride || MODEL_NAME, messages, temperature: 0.2, stream: false });
    const headers = { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) };
    if (MODEL_KEY) headers.Authorization = `Bearer ${MODEL_KEY}`;
    const req = lib.request(url, { method: "POST", headers, timeout: 120000 }, (res) => {
      let body = "";
      res.on("data", (c) => (body += c));
      res.on("end", () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          return reject(new Error(`offense model HTTP ${res.statusCode}: ${body.slice(0, 200)}`));
        }
        try {
          const j = JSON.parse(body);
          const content = j.choices && j.choices[0] && j.choices[0].message && j.choices[0].message.content;
          if (!content) return reject(new Error("offense model returned no content"));
          resolve(content);
        } catch (e) { reject(new Error(`offense model parse error: ${e.message}`)); }
      });
    });
    req.on("error", reject);
    req.on("timeout", () => req.destroy(new Error("offense model timeout (is the GPU instance up + tunnel open?)")));
    req.write(payload);
    req.end();
  });
}

// Structured context only — no raw scan dumps cross into the model prompt either; the
// model reasons over the same typed rows L4 would, plus scope/ROE.
async function gatherContext(engagementId) {
  const eng = await db.query(
    `SELECT id, engagement_type, scope, roe, status,
            executor_host, executor_adb_target, executor_tools
       FROM pentest_engagements WHERE id = $1`, [engagementId]);
  const hosts = await db.query(
    `SELECT ip, hostname, status, ports FROM recon_hosts WHERE engagement_id = $1 ORDER BY ip`, [engagementId]);
  const findings = await db.query(
    `SELECT title, severity, status, affected_asset, affected_assets, refs
       FROM pentest_findings WHERE engagement_id = $1 ORDER BY discovered_at`, [engagementId]);
  // Step 2 of OFFENSE-AGENT-DESIGN.md — last N finalized queue items with outcomes.
  // Gives the model memory of what it tried, what worked, and what failed.
  // Trim command + output to keep prompt size manageable. Most-recent first.
  const queue = await db.query(
    `SELECT seq, title, status,
            LEFT(COALESCE(command, ''), 240) AS command_preview,
            LEFT(COALESCE(output, ''), 600)  AS output_preview,
            completed_at
       FROM soc_queue_items
      WHERE engagement_id = $1
        AND status IN ('done', 'failed', 'cancelled')
      ORDER BY seq DESC
      LIMIT 10`, [engagementId]);
  return {
    engagement: eng.rows[0] || null,
    hosts:    hosts.rows,
    findings: findings.rows,
    queue:    queue.rows,
  };
}

// Wrap the model's logical command for the engagement's executor. For dev-01,
// the command runs as-is. For tablet/phone executors (adb-over-WG), we b64-encode
// the command and route it through adb shell on the target. When the executor's
// tool list includes the `nh` sentinel (Kali chroot installed at
// /data/local/nhsystem), the decoded command is piped into `nh -s` so it runs
// inside the chroot where the real toolchain (nmap, sqlmap, hydra, ...) lives —
// otherwise it runs in stock toybox shell where those binaries don't exist.
// The </dev/null is mandatory per the adb-shell-stdin discipline.
function wrapForExecutor(command, engagement) {
  if (!engagement) return command;
  const host = engagement.executor_host || "dev-01";
  if (host === "dev-01" || !engagement.executor_adb_target) return command;
  const tools = Array.isArray(engagement.executor_tools) ? engagement.executor_tools : [];
  const hasChroot = tools.includes("nh");
  const b64 = Buffer.from(String(command), "utf8").toString("base64");
  const pipe = hasChroot
    ? `echo ${b64} | base64 -d | su -c "/data/local/nhsystem/nh -s"`
    : `echo ${b64} | base64 -d | sh`;
  return `adb -s ${engagement.executor_adb_target} shell '${pipe}' </dev/null`;
}

function parseStep(raw) {
  // Tolerate code fences / stray prose — grab the first JSON object.
  const m = raw.match(/\{[\s\S]*\}/);
  return JSON.parse(m ? m[0] : raw);
}

// Coarse intent bucketing for the offense_telemetry table — keeps audit
// queries readable without storing raw operator text. Cipher (L4) already
// sees the raw intent (it's the caller), so categorization here exposes
// nothing new.
function categorizeIntent(intent) {
  if (!intent) return "default";
  const s = String(intent).toLowerCase();
  if (/(enumerat|recon|discover|scan|enum|fingerprint)/.test(s)) return "enumeration";
  if (/(access|exploit|gain|foothold|initial|rce|cve)/.test(s))   return "access";
  if (/(lateral|pivot|move|escalat)/.test(s))                     return "lateral";
  if (/(exfil|extract|loot|data|credential)/.test(s))             return "exfiltration";
  return "other";
}

// Pre-insert membrane guard. error_message can capture raw model output on
// failures — if it leaks offensive content, redact + warn the operator.
// Patterns mirror membrane-audit.js (kept here so this catches at write time
// even if the auditor patterns drift).
const MEMBRANE_GUARD_PATTERNS = [
  { kind: "cve_id",          regex: /\bCVE-\d{4}-\d{4,7}\b/i },
  { kind: "exploit_keyword", regex: /\b(?:nmap|metasploit|sqlmap|hydra|hashcat|john|payload|exploit|reverse[\s_-]?shell)\b/i },
  { kind: "raw_ip",          regex: /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/ },
  { kind: "credential_file", regex: /\b(?:passwd|shadow|hashes?[\s_-]?dump)\b|\/etc\/(?:passwd|shadow)/i },
];
function sanitizeTelemetryField(value, fieldName, engagementId) {
  if (!value || typeof value !== "string") return value;
  for (const { kind, regex } of MEMBRANE_GUARD_PATTERNS) {
    if (regex.test(value)) {
      console.warn(`[membrane-guard] redacted ${fieldName} on engagement ${engagementId} (matched ${kind}, len=${value.length})`);
      return `<<membrane-guard redacted ${kind} from ${fieldName}>>`;
    }
  }
  return value;
}

// Append one row to offense_telemetry. NEVER throws — telemetry failure
// must never break advance_offense.
async function insertTelemetry(tel) {
  try {
    // Pre-insert sanitization — primary risk is error_message which captures
    // raw model output on failure paths.
    const safeErrorMessage = sanitizeTelemetryField(tel.errorMessage, "error_message", tel.engagementId);
    await db.query(
      `INSERT INTO offense_telemetry
         (engagement_id, queue_item_id, model_used, intent_category,
          n_hosts, n_findings, step_queued, in_scope, n_references,
          latency_ms, error_message)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
      [tel.engagementId, tel.queueItemId, tel.model, tel.intentCategory,
       tel.nHosts, tel.nFindings, tel.stepQueued, tel.inScope, tel.nReferences,
       tel.latencyMs, safeErrorMessage]);
  } catch (e) {
    console.error("[offense-engine] telemetry insert failed:", e.message);
  }
}

// Advance the engagement by one offensive step. Returns ONLY a sanitized label —
// the command/rationale/references stay server-side in the PA queue.
// modelOverride: optional model tag for in-harness benchmarking; queue title gets
// prefixed with [<model_tag>] so the operator can attribute the step in the SOC app.
async function advanceOffense(engagementId, intent, modelOverride) {
  if (!engagementId) throw new Error("engagement_id required");
  const ctx = await gatherContext(engagementId);
  if (!ctx.engagement) throw new Error(`engagement ${engagementId} not found`);

  const effectiveModel = modelOverride || MODEL_NAME;
  const startMs = Date.now();
  const tel = {
    engagementId,
    queueItemId: null,
    model: effectiveModel,
    intentCategory: categorizeIntent(intent),
    nHosts: ctx.hosts.length,
    nFindings: ctx.findings.length,
    stepQueued: false,
    inScope: null,
    nReferences: 0,
    latencyMs: 0,
    errorMessage: null,
  };

  const execHost = ctx.engagement.executor_host || "dev-01";
  const execTools = Array.isArray(ctx.engagement.executor_tools)
    ? ctx.engagement.executor_tools
    : (ctx.engagement.executor_tools && typeof ctx.engagement.executor_tools === "object"
        ? Object.values(ctx.engagement.executor_tools) : []);
  const execHint = (execHost === "dev-01")
    ? "(commands run on a kali toolhost; full network access is via dev-01's LAN/VPN)"
    : `(commands will run ON the executor itself — the executor is on the same LAN as the targets; do NOT prefix with adb / ssh, just write the command as if you were on a regular Linux shell on the target LAN)`;

  // Executor capability caveats — surfaced to BOTH reasoning + generation so the
  // agent stops burning iterations rediscovering kernel/SELinux limits. Mirrors
  // offense-agent-tools.js getEngagementState's executor_caps_note (keep in sync);
  // that note only reaches Cipher via the MCP tool — the offense agent loop never
  // saw it, which is why every nmap on the tablet failed on netlink permission
  // denied even though the chroot, wrap, and tool list were all correct.
  const executorCaps = execTools.includes("nh")
    ? [
        "Executor quirks (Kali ARM64 chroot via `nh -s` on rooted Samsung tablet):",
        "  - Samsung kernel + SELinux BLOCK netlink (RTM_GETROUTE) and AF_PACKET even with CAP_NET_RAW.",
        "  - nmap MUST use `-sT -Pn` (TCP-connect, skip host discovery). Without `-Pn`, nmap does a route lookup and fails with `route_dst_netlink: if_indextoname(2) failed: 13 Permission denied`.",
        "  - NO SYN scans (`-sS`), NO ICMP discovery (`-PE` / `-sn -PE`), NO `-O` OS fingerprinting, NO `arp-scan` — all need raw sockets.",
        "  - TCP-connect tools work fine: `curl`, `nc -z`, `bash /dev/tcp`, `nuclei`, `whatweb`, `ffuf`, `gobuster`, `smbclient`, `smbmap`, `crackmapexec`, `netexec`, `dig`, `host`, `wpscan`, `sqlmap`, `hydra`, `nikto`.",
        "  - For host discovery use `nmap -sn -PS<port>` (TCP probe) against a known-likely-open port (22, 80, 443, 8080), NOT `-PE` (ICMP).",
      ].join("\n")
    : null;

  // Queue history (most recent finalized attempts + outcomes). Gives the model
  // memory of what it tried so it doesn't repeat itself and can pivot on failure.
  const historyLines = (ctx.queue || []).map((q) => {
    const cmd = (q.command_preview || "").replace(/\s+/g, " ").trim();
    const out = (q.output_preview || "").replace(/\s+/g, " ").trim();
    return `  - seq=${q.seq} [${q.status}] "${q.title || ""}"; command: ${cmd || "(none)"}; output: ${out || "(empty)"}`;
  });
  const historyBlock = historyLines.length
    ? `Recent queue history (most recent first; learn from these — do NOT repeat failed approaches):\n${historyLines.join("\n")}`
    : "Recent queue history: (none — this is the first attempt on this engagement)";

  // ── REASONING stage: full engagement context → pick next sub-task (no command) ──
  const reasoningUserMsg = [
    `Engagement: type=${ctx.engagement.engagement_type || "?"} status=${ctx.engagement.status || "?"}`,
    `Scope/ROE: ${JSON.stringify({ scope: ctx.engagement.scope, roe: ctx.engagement.roe })}`,
    `Operator intent: ${intent || "advance the engagement toward its objective"}`,
    `Executor: ${execHost} ${execHint}`,
    ...(executorCaps ? [executorCaps] : []),
    `Tools available on the executor: ${execTools.length ? execTools.join(", ") : "(unknown — assume only POSIX-portable shell tools)"}`,
    `Structured recon (hosts/ports/services): ${JSON.stringify(ctx.hosts)}`,
    `Findings so far: ${JSON.stringify(ctx.findings)}`,
    historyBlock,
    "Pick the next in-scope sub-task as strict JSON. If a similar approach already failed in the queue history, pivot to a different technique.",
  ].join("\n");

  let subtask;
  try {
    const reasoningRaw = await chatCompletion([
      { role: "system", content: REASONING_SYSTEM_PROMPT },
      { role: "user",   content: reasoningUserMsg },
    ], modelOverride);
    subtask = parseStep(reasoningRaw);
  } catch (e) {
    tel.latencyMs = Date.now() - startMs;
    tel.errorMessage = `reasoning: ${e.message}`;
    await insertTelemetry(tel);
    throw e instanceof Error ? e : new Error(`offense model reasoning error: ${String(e)}`);
  }

  tel.inScope = subtask && subtask.in_scope !== false;
  if (!subtask || subtask.in_scope === false) {
    tel.latencyMs = Date.now() - startMs;
    await insertTelemetry(tel);
    return { queued: false, engagement_id: engagementId,
             reason: "the offense model judged no in-scope sub-task is available" };
  }

  // ── GENERATION stage: just the chosen sub-task + tools → exact command ──
  // Recent command shapes from history give Generation a feel for what's been
  // tried at the command level (failed shapes are still useful — model avoids them).
  const recentCmds = (ctx.queue || []).slice(0, 5).map((q) =>
    `  - [${q.status}] ${(q.command_preview || "").replace(/\s+/g, " ").slice(0, 100)}`
  ).join("\n");

  const generationUserMsg = [
    `Sub-task chosen by reasoning: ${subtask.subtask || "(empty)"}`,
    `Rationale: ${subtask.rationale || "(none)"}`,
    `Expected payoff: ${subtask.expected_payoff || "(unspecified)"}`,
    subtask.references && subtask.references.length
      ? `References from reasoning: ${subtask.references.join(", ")}`
      : "References from reasoning: (none)",
    `Executor: ${execHost} ${execHint}`,
    ...(executorCaps ? [executorCaps] : []),
    `Tools available on the executor: ${execTools.length ? execTools.join(", ") : "(unknown — POSIX-portable only)"}`,
    recentCmds
      ? `Recent commands attempted on this engagement (do NOT propose a command identical or near-identical to a failed one):\n${recentCmds}`
      : "Recent commands attempted: (none)",
    "Translate the sub-task into the exact shell command, as strict JSON.",
  ].join("\n");

  let step;
  try {
    const generationRaw = await chatCompletion([
      { role: "system", content: GENERATION_SYSTEM_PROMPT },
      { role: "user",   content: generationUserMsg },
    ], modelOverride);
    step = parseStep(generationRaw);
  } catch (e) {
    tel.latencyMs = Date.now() - startMs;
    tel.errorMessage = `generation: ${e.message}`;
    await insertTelemetry(tel);
    throw e instanceof Error ? e : new Error(`offense model generation error: ${String(e)}`);
  }

  tel.latencyMs = Date.now() - startMs;
  // n_references — prefer Generation's (more specific); fall back to Reasoning's.
  tel.nReferences =
    (step && Array.isArray(step.references) ? step.references.length : 0) ||
    (subtask && Array.isArray(subtask.references) ? subtask.references.length : 0);

  if (!step || !step.command) {
    await insertTelemetry(tel);
    return { queued: false, engagement_id: engagementId,
             reason: "the generation stage returned no executable command" };
  }

  const seqRow = await db.query(
    `SELECT COALESCE(MAX(seq), 0) + 1 AS next FROM soc_queue_items WHERE engagement_id = $1`, [engagementId]);
  const seq = seqRow.rows[0].next;

  // The offensive bytes (command / rationale / references) land in the queue for the PA.
  // They are deliberately NOT returned to the caller (L4).
  // description = Reasoning's rationale (the WHY) — Generation focuses on the WHAT (command),
  // so we join the two layers for full operator-side context in the SOC app.
  const titleBase = step.title || subtask.subtask || `Offensive step ${seq}`;
  const title = modelOverride ? `[${modelOverride}] ${titleBase}` : titleBase;
  const description = subtask.rationale
    ? (subtask.expected_payoff ? `${subtask.rationale}\n\nExpected payoff: ${subtask.expected_payoff}` : subtask.rationale)
    : (step.rationale || null);
  const wrappedCommand = wrapForExecutor(step.command, ctx.engagement);
  // Membrane-handled origin: offense engine writes the L3 model's authored
  // command into soc_queue_items.command. Bypass the cipher-exploit-write
  // trigger — the model is the legitimate author here. See db.js withBypass +
  // memory feedback_soc_observer_role.md.
  const ins = await db.withBypass('offense_engine', (client) => client.query(
    `INSERT INTO soc_queue_items (engagement_id, seq, title, description, command, expected_artifact, status)
     VALUES ($1, $2, $3, $4, $5, $6, 'pending') RETURNING id, seq`,
    [engagementId, seq, title,
     description, wrappedCommand, step.expected_artifact || null]));

  tel.queueItemId = ins.rows[0].id;
  tel.stepQueued = true;
  await insertTelemetry(tel);

  return {
    queued: true,
    queue_id: ins.rows[0].id,
    seq: ins.rows[0].seq,
    engagement_id: engagementId,
    note: "Step synthesized server-side by the L3 model and queued for the PA. Its contents are intentionally not surfaced here (membrane) — the operator sees the command in the SOC queue.",
  };
}

module.exports = { advanceOffense };
