"use strict";
// offense-engine.js — L3 offense-synthesis (dir_1780577251265)
//
// WHY THIS EXISTS: SOC sessions trip the usage-policy classifier when the frontier model
// (Claude / L4) reasons about the offensive operation itself — which creds to try, which
// exploit applies, what order to attack. That reasoning IS the flagged activity, and no
// membrane on Claude's INPUT fixes it, because the content is generated BY Claude. The
// fix is to move that synthesis onto a self-hosted model with no classifier: this module
// reads the STRUCTURED findings for an engagement, asks the self-hosted model for the
// single next in-scope step, and writes it to the PA queue. The offensive output
// (command / rationale / refs) is persisted to soc_queue_items ONLY — advanceOffense
// returns a sanitized label, never the offensive bytes. That boundary is what keeps
// offensive content out of L4's context. See SOC-PIPELINE-ARCHITECTURE.md.

const http = require("http");
const https = require("https");
const { URL } = require("url");
const db = require("./db");

// Configurable so we can benchmark Qwen-3.x-32B vs DeepSeek in-harness with no code
// change. Endpoint is the OpenAI-compatible base of a self-hosted server (Ollama/vLLM)
// reached over an SSH tunnel from the bridge (see SOC-OFFENSE-MODEL-RUNBOOK.md).
const MODEL_URL  = process.env.OFFENSE_MODEL_URL  || "http://127.0.0.1:11434/v1";
const MODEL_NAME = process.env.OFFENSE_MODEL_NAME || "qwen2.5-coder:32b"; // placeholder; set per-benchmark
const MODEL_KEY  = process.env.OFFENSE_MODEL_KEY  || "";

const SYSTEM_PROMPT = [
  "You are the offensive-synthesis engine for an AUTHORIZED penetration-testing engagement.",
  "You are given the engagement scope/ROE plus the structured recon and findings.",
  "Propose EXACTLY ONE next concrete offensive step that stays strictly within scope.",
  "Reference public PoCs only by ID (CVE / ExploitDB EDB-id / Metasploit module path).",
  "Respond as STRICT JSON, no prose, no code fences:",
  '{"title":"short label","rationale":"why this step","command":"exact shell command for the operator","expected_artifact":"what success looks like","references":["CVE-... | EDB-... | exploit/..."],"in_scope":true}',
  'If no in-scope step exists, return {"in_scope":false,"command":""}.',
].join("\n");

function chatCompletion(messages, modelOverride) {
  return new Promise((resolve, reject) => {
    const base = MODEL_URL.replace(/\/+$/, "");
    const url = new URL(base + "/chat/completions");
    const lib = url.protocol === "https:" ? https : http;
    const payload = JSON.stringify({ model: modelOverride || MODEL_NAME, messages, temperature: 0.2, stream: false });
    const headers = { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) };
    if (MODEL_KEY) headers.Authorization = `Bearer ${MODEL_KEY}`;
    const req = lib.request(url, { method: "POST", headers, timeout: 120000 }, (res) => {
      let body = "";
      res.on("data", (c) => (body += c));
      res.on("end", () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          return reject(new Error(`offense model HTTP ${res.statusCode}: ${body.slice(0, 200)}`));
        }
        try {
          const j = JSON.parse(body);
          const content = j.choices && j.choices[0] && j.choices[0].message && j.choices[0].message.content;
          if (!content) return reject(new Error("offense model returned no content"));
          resolve(content);
        } catch (e) { reject(new Error(`offense model parse error: ${e.message}`)); }
      });
    });
    req.on("error", reject);
    req.on("timeout", () => req.destroy(new Error("offense model timeout (is the GPU instance up + tunnel open?)")));
    req.write(payload);
    req.end();
  });
}

// Structured context only — no raw scan dumps cross into the model prompt either; the
// model reasons over the same typed rows L4 would, plus scope/ROE.
async function gatherContext(engagementId) {
  const eng = await db.query(
    `SELECT id, engagement_type, scope, roe, status,
            executor_host, executor_adb_target, executor_tools
       FROM pentest_engagements WHERE id = $1`, [engagementId]);
  const hosts = await db.query(
    `SELECT ip, hostname, status, ports FROM recon_hosts WHERE engagement_id = $1 ORDER BY ip`, [engagementId]);
  const findings = await db.query(
    `SELECT title, severity, status, affected_asset, affected_assets, refs
       FROM pentest_findings WHERE engagement_id = $1 ORDER BY discovered_at`, [engagementId]);
  // Step 2 of OFFENSE-AGENT-DESIGN.md — last N finalized queue items with outcomes.
  // Gives the model memory of what it tried, what worked, and what failed.
  // Trim command + output to keep prompt size manageable. Most-recent first.
  const queue = await db.query(
    `SELECT seq, title, status,
            LEFT(COALESCE(command, ''), 240) AS command_preview,
            LEFT(COALESCE(output, ''), 600)  AS output_preview,
            completed_at
       FROM soc_queue_items
      WHERE engagement_id = $1
        AND status IN ('done', 'failed', 'cancelled')
      ORDER BY seq DESC
      LIMIT 10`, [engagementId]);
  return {
    engagement: eng.rows[0] || null,
    hosts:    hosts.rows,
    findings: findings.rows,
    queue:    queue.rows,
  };
}

// Wrap the model's logical command for the engagement's executor. For dev-01,
// the command runs as-is. For tablet/phone executors (adb-over-WG), we b64-encode
// the command and route it through adb shell on the target — the SSH-to-dev-01
// transport layer is unchanged; dev-01 hosts adb and reaches the tablet via WG.
// The </dev/null is mandatory per the adb-shell-stdin discipline.
function wrapForExecutor(command, engagement) {
  if (!engagement) return command;
  const host = engagement.executor_host || "dev-01";
  if (host === "dev-01" || !engagement.executor_adb_target) return command;
  const b64 = Buffer.from(String(command), "utf8").toString("base64");
  return `adb -s ${engagement.executor_adb_target} shell "echo ${b64} | base64 -d | sh" </dev/null`;
}

function parseStep(raw) {
  // Tolerate code fences / stray prose — grab the first JSON object.
  const m = raw.match(/\{[\s\S]*\}/);
  return JSON.parse(m ? m[0] : raw);
}

// Coarse intent bucketing for the offense_telemetry table — keeps audit
// queries readable without storing raw operator text. Cipher (L4) already
// sees the raw intent (it's the caller), so categorization here exposes
// nothing new.
function categorizeIntent(intent) {
  if (!intent) return "default";
  const s = String(intent).toLowerCase();
  if (/(enumerat|recon|discover|scan|enum|fingerprint)/.test(s)) return "enumeration";
  if (/(access|exploit|gain|foothold|initial|rce|cve)/.test(s))   return "access";
  if (/(lateral|pivot|move|escalat)/.test(s))                     return "lateral";
  if (/(exfil|extract|loot|data|credential)/.test(s))             return "exfiltration";
  return "other";
}

// Append one row to offense_telemetry. NEVER throws — telemetry failure
// must never break advance_offense.
async function insertTelemetry(tel) {
  try {
    await db.query(
      `INSERT INTO offense_telemetry
         (engagement_id, queue_item_id, model_used, intent_category,
          n_hosts, n_findings, step_queued, in_scope, n_references,
          latency_ms, error_message)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
      [tel.engagementId, tel.queueItemId, tel.model, tel.intentCategory,
       tel.nHosts, tel.nFindings, tel.stepQueued, tel.inScope, tel.nReferences,
       tel.latencyMs, tel.errorMessage]);
  } catch (e) {
    console.error("[offense-engine] telemetry insert failed:", e.message);
  }
}

// Advance the engagement by one offensive step. Returns ONLY a sanitized label —
// the command/rationale/references stay server-side in the PA queue.
// modelOverride: optional model tag for in-harness benchmarking; queue title gets
// prefixed with [<model_tag>] so the operator can attribute the step in the SOC app.
async function advanceOffense(engagementId, intent, modelOverride) {
  if (!engagementId) throw new Error("engagement_id required");
  const ctx = await gatherContext(engagementId);
  if (!ctx.engagement) throw new Error(`engagement ${engagementId} not found`);

  const effectiveModel = modelOverride || MODEL_NAME;
  const startMs = Date.now();
  const tel = {
    engagementId,
    queueItemId: null,
    model: effectiveModel,
    intentCategory: categorizeIntent(intent),
    nHosts: ctx.hosts.length,
    nFindings: ctx.findings.length,
    stepQueued: false,
    inScope: null,
    nReferences: 0,
    latencyMs: 0,
    errorMessage: null,
  };

  const execHost = ctx.engagement.executor_host || "dev-01";
  const execTools = Array.isArray(ctx.engagement.executor_tools)
    ? ctx.engagement.executor_tools
    : (ctx.engagement.executor_tools && typeof ctx.engagement.executor_tools === "object"
        ? Object.values(ctx.engagement.executor_tools) : []);
  const execHint = (execHost === "dev-01")
    ? "(commands run on a kali toolhost; full network access is via dev-01's LAN/VPN)"
    : `(commands will run ON the executor itself — the executor is on the same LAN as the targets; do NOT prefix with adb / ssh, just write the command as if you were on a regular Linux shell on the target LAN)`;

  // Queue history (most recent finalized attempts + outcomes). Gives the model
  // memory of what it tried so it doesn't repeat itself and can pivot on failure.
  const historyLines = (ctx.queue || []).map((q) => {
    const cmd = (q.command_preview || "").replace(/\s+/g, " ").trim();
    const out = (q.output_preview || "").replace(/\s+/g, " ").trim();
    return `  - seq=${q.seq} [${q.status}] "${q.title || ""}"; command: ${cmd || "(none)"}; output: ${out || "(empty)"}`;
  });
  const historyBlock = historyLines.length
    ? `Recent queue history (most recent first; learn from these — do NOT repeat failed approaches):\n${historyLines.join("\n")}`
    : "Recent queue history: (none — this is the first attempt on this engagement)";

  const userMsg = [
    `Engagement: type=${ctx.engagement.engagement_type || "?"} status=${ctx.engagement.status || "?"}`,
    `Scope/ROE: ${JSON.stringify({ scope: ctx.engagement.scope, roe: ctx.engagement.roe })}`,
    `Operator intent: ${intent || "advance the engagement toward its objective"}`,
    `Executor: ${execHost} ${execHint}`,
    `Tools available on the executor: ${execTools.length ? execTools.join(", ") : "(unknown — pick from POSIX-portable shell tools only)"}`,
    `Structured recon (hosts/ports/services): ${JSON.stringify(ctx.hosts)}`,
    `Findings so far: ${JSON.stringify(ctx.findings)}`,
    historyBlock,
    "Propose the single next in-scope offensive step as strict JSON. Pick commands ONLY from the listed tools — do not invent tool names. If a similar approach already failed in the queue history, pivot to a different technique.",
  ].join("\n");

  let raw, step;
  try {
    raw = await chatCompletion([
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: userMsg },
    ], modelOverride);
    tel.latencyMs = Date.now() - startMs;
    step = parseStep(raw);
  } catch (e) {
    tel.latencyMs = Date.now() - startMs;
    tel.errorMessage = e.message;
    await insertTelemetry(tel);
    throw e instanceof Error ? e : new Error(`offense model error: ${String(e)}`);
  }

  tel.inScope = step && step.in_scope !== false;
  tel.nReferences = step && Array.isArray(step.references) ? step.references.length : 0;

  if (!step || step.in_scope === false || !step.command) {
    await insertTelemetry(tel);
    return { queued: false, engagement_id: engagementId,
             reason: "the offense model judged no in-scope step is available" };
  }

  const seqRow = await db.query(
    `SELECT COALESCE(MAX(seq), 0) + 1 AS next FROM soc_queue_items WHERE engagement_id = $1`, [engagementId]);
  const seq = seqRow.rows[0].next;

  // The offensive bytes (command / rationale / references) land in the queue for the PA.
  // They are deliberately NOT returned to the caller (L4).
  const titleBase = step.title || `Offensive step ${seq}`;
  const title = modelOverride ? `[${modelOverride}] ${titleBase}` : titleBase;
  const wrappedCommand = wrapForExecutor(step.command, ctx.engagement);
  const ins = await db.query(
    `INSERT INTO soc_queue_items (engagement_id, seq, title, description, command, expected_artifact, status)
     VALUES ($1, $2, $3, $4, $5, $6, 'pending') RETURNING id, seq`,
    [engagementId, seq, title,
     step.rationale || null, wrappedCommand, step.expected_artifact || null]);

  tel.queueItemId = ins.rows[0].id;
  tel.stepQueued = true;
  await insertTelemetry(tel);

  return {
    queued: true,
    queue_id: ins.rows[0].id,
    seq: ins.rows[0].seq,
    engagement_id: engagementId,
    note: "Step synthesized server-side by the L3 model and queued for the PA. Its contents are intentionally not surfaced here (membrane) — the operator sees the command in the SOC queue.",
  };
}

module.exports = { advanceOffense };
