services:
  web:
    build: ./web
    container_name: ozzulab-sqli-i1-web
    networks: { labnet: { ipv4_address: 10.10.30.20 } }
  db:
    build: ./db
    container_name: ozzulab-sqli-i1-db
    networks: { labnet: { ipv4_address: 10.10.30.30 } }
networks:
  labnet:
    ipam: { config: [ { subnet: 10.10.30.0/24 } ] }
