#!/usr/bin/env bash
# render-ssh-config.sh — Emit ~/.ssh/config block from infra/devices.json.
#
# Usage:
#   scripts/render-ssh-config.sh           # print to stdout
#   scripts/render-ssh-config.sh --apply   # write to ~/.ssh/config (replacing
#                                          # existing # OZZU-MANAGED block)
#
# Idempotent. The managed block is delimited by:
#   # ---- OZZU-MANAGED:BEGIN ----
#   ...
#   # ---- OZZU-MANAGED:END ----
# Anything outside those markers in ~/.ssh/config is preserved.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/infra.sh"

BEGIN_MARK="# ---- OZZU-MANAGED:BEGIN ----"
END_MARK="# ---- OZZU-MANAGED:END ----"

render() {
  echo "$BEGIN_MARK"
  echo "# Generated by scripts/render-ssh-config.sh from infra/devices.json."
  echo "# Edit devices.json and re-run --apply; do NOT edit between these markers."
  echo

  jq -r '.devices | to_entries[] | select(.value.ssh_user) | @json' "$OZZU_INFRA_JSON" | while read -r entry; do
    name=$(echo "$entry"   | jq -r '.key')
    user=$(echo "$entry"   | jq -r '.value.ssh_user')
    alias=$(echo "$entry"  | jq -r '.value.ssh_alias // empty')
    host=$(echo "$entry"   | jq -r '.value.wg_ip // .value.lan_ip // empty')
    key=$(echo "$entry"    | jq -r '.value.ssh_key // empty')
    jump=$(echo "$entry"   | jq -r '.value.ssh_jump // empty')
    kex_legacy=$(echo "$entry" | jq -r '.value.ssh_kex_legacy // false')
    [ -z "$host" ] && continue

    aliases="$name"
    [ -n "$alias" ] && [ "$alias" != "$name" ] && aliases="$alias $name"

    echo "Host $aliases"
    echo "    HostName $host"
    echo "    User $user"
    [ -n "$key" ] && echo "    IdentityFile $key" && echo "    IdentitiesOnly yes"
    [ -n "$jump" ] && echo "    ProxyJump $jump"
    if [ "$kex_legacy" = "true" ]; then
      echo "    KexAlgorithms +diffie-hellman-group14-sha1"
      echo "    HostKeyAlgorithms +ssh-rsa"
    fi
    echo "    StrictHostKeyChecking no"
    echo
  done

  echo "$END_MARK"
}

apply() {
  local target="$HOME/.ssh/config"
  local rendered
  rendered=$(render)

  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"

  if [ ! -f "$target" ]; then
    printf '%s\n' "$rendered" > "$target"
    chmod 600 "$target"
    echo "Wrote $target (new file)"
    return
  fi

  # Strip any prior managed block, prepend the new one.
  local tmp
  tmp=$(mktemp)
  awk -v BEGIN_M="$BEGIN_MARK" -v END_M="$END_MARK" '
    $0 == BEGIN_M { skip=1; next }
    $0 == END_M   { skip=0; next }
    !skip
  ' "$target" > "$tmp"

  {
    printf '%s\n\n' "$rendered"
    cat "$tmp"
  } > "$target.new"
  mv "$target.new" "$target"
  rm -f "$tmp"
  chmod 600 "$target"
  echo "Updated $target (managed block replaced)"
}

case "${1:-}" in
  --apply) apply ;;
  --help|-h)
    sed -n '2,15p' "${BASH_SOURCE[0]}"
    ;;
  *) render ;;
esac
