// Username enumeration module — Sherlock-style HTTP HEAD checks
// 324 platforms sourced from Sherlock project (status_code detection compatible)
// No API keys needed, just HTTP requests to public profile URLs

const PLATFORMS = [
  { name: "2Dimensions", url: "https://2Dimensions.com/a/{}", category: "other" },
  { name: "7Cups", url: "https://www.7cups.com/@{}", category: "other" },
  { name: "9GAG", url: "https://www.9gag.com/u/{}", category: "other" },
  { name: "About.me", url: "https://about.me/{}", category: "identity" },
  { name: "Academia.edu", url: "https://independent.academia.edu/{}", category: "other" },
  { name: "Airbit", url: "https://airbit.com/{}", category: "other" },
  { name: "Airliners", url: "https://www.airliners.net/user/{}/profile/photos", category: "other" },
  { name: "Anilist", url: "https://anilist.co/user/{}/", category: "media" },
  { name: "Aparat", url: "https://www.aparat.com/{}/", category: "other" },
  { name: "Apple Developer", url: "https://developer.apple.com/forums/profile/{}", category: "other" },
  { name: "Archive of Our Own", url: "https://archiveofourown.org/users/{}", category: "other" },
  { name: "Arduino Forum", url: "https://forum.arduino.cc/u/{}/summary", category: "other" },
  { name: "ArtStation", url: "https://www.artstation.com/{}", category: "design" },
  { name: "Asciinema", url: "https://asciinema.org/~{}", category: "other" },
  { name: "Ask Fedora", url: "https://ask.fedoraproject.org/u/{}", category: "other" },
  { name: "Atcoder", url: "https://atcoder.jp/users/{}", category: "other" },
  { name: "Audiojungle", url: "https://audiojungle.net/user/{}", category: "other" },
  { name: "Autofrage", url: "https://www.autofrage.net/nutzer/{}", category: "other" },
  { name: "Bandcamp", url: "https://www.bandcamp.com/{}", category: "media" },
  { name: "Behance", url: "https://www.behance.net/{}", category: "design" },
  { name: "Bezuzyteczna", url: "https://bezuzyteczna.pl/uzytkownicy/{}", category: "other" },
  { name: "BiggerPockets", url: "https://www.biggerpockets.com/users/{}", category: "other" },
  { name: "BioHacking", url: "https://forum.dangerousthings.com/u/{}", category: "other" },
  { name: "BitBucket", url: "https://bitbucket.org/{}/", category: "development" },
  { name: "Bitwarden Forum", url: "https://community.bitwarden.com/u/{}/summary", category: "other" },
  { name: "Blipfoto", url: "https://www.blipfoto.com/{}", category: "other" },
  { name: "Blogger", url: "https://{}.blogspot.com", category: "content" },
  { name: "Bluesky", url: "https://bsky.app/profile/{}.bsky.social", category: "social" },
  { name: "BongaCams", url: "https://pt.bongacams.com/profile/{}", category: "other" },
  { name: "Bookcrossing", url: "https://www.bookcrossing.com/mybookshelf/{}/", category: "other" },
  { name: "BraveCommunity", url: "https://community.brave.com/u/{}/", category: "other" },
  { name: "BugCrowd", url: "https://bugcrowd.com/{}", category: "security" },
  { name: "BuyMeACoffee", url: "https://buymeacoff.ee/{}", category: "content" },
  { name: "BuzzFeed", url: "https://buzzfeed.com/{}", category: "other" },
  { name: "CGTrader", url: "https://www.cgtrader.com/{}", category: "other" },
  { name: "CNET", url: "https://www.cnet.com/profiles/{}/", category: "other" },
  { name: "CSSBattle", url: "https://cssbattle.dev/player/{}", category: "other" },
  { name: "CTAN", url: "https://ctan.org/author/{}", category: "other" },
  { name: "Caddy Community", url: "https://caddy.community/u/{}/summary", category: "other" },
  { name: "Car Talk Community", url: "https://community.cartalk.com/u/{}/summary", category: "other" },
  { name: "CashApp", url: "https://cash.app/${}", category: "finance" },
  { name: "Cfx.re Forum", url: "https://forum.cfx.re/u/{}/summary", category: "other" },
  { name: "Championat", url: "https://www.championat.com/user/{}", category: "other" },
  { name: "Chaos", url: "https://chaos.social/@{}", category: "other" },
  { name: "ChaturBate", url: "https://chaturbate.com/{}", category: "other" },
  { name: "Choice Community", url: "https://choice.community/u/{}/summary", category: "other" },
  { name: "Chollometro", url: "https://www.chollometro.com/profile/{}", category: "other" },
  { name: "Clapper", url: "https://clapperapp.com/{}", category: "other" },
  { name: "CloudflareCommunity", url: "https://community.cloudflare.com/u/{}", category: "other" },
  { name: "Clubhouse", url: "https://www.clubhouse.com/@{}", category: "social" },
  { name: "Codeberg", url: "https://codeberg.org/{}", category: "development" },
  { name: "Codeforces", url: "https://codeforces.com/profile/{}", category: "development" },
  { name: "Codepen", url: "https://codepen.io/{}", category: "development" },
  { name: "Coderwall", url: "https://coderwall.com/{}", category: "other" },
  { name: "Codewars", url: "https://www.codewars.com/users/{}", category: "development" },
  { name: "Coinvote", url: "https://coinvote.cc/profile/{}", category: "other" },
  { name: "ColourLovers", url: "https://www.colourlovers.com/lover/{}", category: "other" },
  { name: "Coroflot", url: "https://www.coroflot.com/{}", category: "other" },
  { name: "Credly", url: "https://www.credly.com/users/{}", category: "other" },
  { name: "Crevado", url: "https://{}.crevado.com", category: "other" },
  { name: "Crowdin", url: "https://crowdin.com/profile/{}", category: "other" },
  { name: "Cryptomator Forum", url: "https://community.cryptomator.org/u/{}", category: "other" },
  { name: "CurseForge", url: "https://www.curseforge.com/members/{}/projects", category: "gaming" },
  { name: "CyberDefenders", url: "https://cyberdefenders.org/p/{}", category: "other" },
  { name: "DEV Community", url: "https://dev.to/{}", category: "development" },
  { name: "DailyMotion", url: "https://www.dailymotion.com/{}", category: "media" },
  { name: "Discogs", url: "https://www.discogs.com/user/{}", category: "media" },
  { name: "Discuss.Elastic.co", url: "https://discuss.elastic.co/u/{}", category: "other" },
  { name: "Disqus", url: "https://disqus.com/{}", category: "other" },
  { name: "Docker Hub", url: "https://hub.docker.com/u/{}/", category: "development" },
  { name: "Eintracht Frankfurt Forum", url: "https://community.eintracht.de/fans/{}", category: "other" },
  { name: "Empretienda AR", url: "https://{}.empretienda.com.ar", category: "other" },
  { name: "Envato Forum", url: "https://forums.envato.com/u/{}", category: "other" },
  { name: "Erome", url: "https://www.erome.com/{}", category: "other" },
  { name: "Exposure", url: "https://{}.exposure.co/", category: "gaming" },
  { name: "EyeEm", url: "https://www.eyeem.com/u/{}", category: "other" },
  { name: "F3.cool", url: "https://f3.cool/{}/", category: "other" },
  { name: "Fameswap", url: "https://fameswap.com/user/{}", category: "other" },
  { name: "Fandom", url: "https://www.fandom.com/u/{}", category: "other" },
  { name: "Finanzfrage", url: "https://www.finanzfrage.net/nutzer/{}", category: "other" },
  { name: "Flickr", url: "https://www.flickr.com/people/{}", category: "media" },
  { name: "Flightradar24", url: "https://my.flightradar24.com/{}", category: "other" },
  { name: "Flipboard", url: "https://flipboard.com/@{}", category: "other" },
  { name: "FortniteTracker", url: "https://fortnitetracker.com/profile/all/{}", category: "other" },
  { name: "Fosstodon", url: "https://fosstodon.org/@{}", category: "other" },
  { name: "Framapiaf", url: "https://framapiaf.org/@{}", category: "other" },
  { name: "Freesound", url: "https://freesound.org/people/{}/", category: "other" },
  { name: "GameFAQs", url: "https://gamefaqs.gamespot.com/community/{}", category: "gaming" },
  { name: "Gamespot", url: "https://www.gamespot.com/profile/{}/", category: "gaming" },
  { name: "GeeksforGeeks", url: "https://auth.geeksforgeeks.org/user/{}", category: "other" },
  { name: "Genius (Artists)", url: "https://genius.com/artists/{}", category: "media" },
  { name: "Genius (Users)", url: "https://genius.com/{}", category: "media" },
  { name: "Gesundheitsfrage", url: "https://www.gesundheitsfrage.net/nutzer/{}", category: "other" },
  { name: "GetMyUni", url: "https://www.getmyuni.com/user/{}", category: "other" },
  { name: "Giant Bomb", url: "https://www.giantbomb.com/profile/{}/", category: "other" },
  { name: "GitBook", url: "https://{}.gitbook.io/", category: "other" },
  { name: "GitHub", url: "https://www.github.com/{}", category: "development" },
  { name: "Gitea", url: "https://gitea.com/{}", category: "development" },
  { name: "Gitee", url: "https://gitee.com/{}", category: "development" },
  { name: "GoodReads", url: "https://www.goodreads.com/{}", category: "other" },
  { name: "Gradle", url: "https://plugins.gradle.org/u/{}", category: "other" },
  { name: "Gravatar", url: "http://en.gravatar.com/{}", category: "identity" },
  { name: "Gutefrage", url: "https://www.gutefrage.net/nutzer/{}", category: "other" },
  { name: "HackMD", url: "https://hackmd.io/@{}", category: "other" },
  { name: "HackTheBox", url: "https://forum.hackthebox.com/u/{}", category: "social" },
  { name: "Hackaday", url: "https://hackaday.io/{}", category: "other" },
  { name: "HackerEarth", url: "https://hackerearth.com/@{}", category: "other" },
  { name: "HackerSploit", url: "https://forum.hackersploit.org/u/{}", category: "other" },
  { name: "Harvard Scholar", url: "https://scholar.harvard.edu/{}", category: "other" },
  { name: "Hashnode", url: "https://hashnode.com/@{}", category: "content" },
  { name: "HotUKdeals", url: "https://www.hotukdeals.com/profile/{}", category: "other" },
  { name: "Houzz", url: "https://houzz.com/user/{}", category: "other" },
  { name: "HubPages", url: "https://hubpages.com/@{}", category: "other" },
  { name: "Hugging Face", url: "https://huggingface.co/{}", category: "development" },
  { name: "IFTTT", url: "https://www.ifttt.com/p/{}", category: "other" },
  { name: "Icons8 Community", url: "https://community.icons8.com/u/{}/summary", category: "other" },
  { name: "Ifunny", url: "https://ifunny.co/user/{}", category: "other" },
  { name: "ImgUp.cz", url: "https://imgup.cz/{}", category: "other" },
  { name: "Imgur", url: "https://imgur.com/user/{}", category: "other" },
  { name: "Instagram", url: "https://instagram.com/{}", category: "social" },
  { name: "Instapaper", url: "https://www.instapaper.com/p/{}", category: "other" },
  { name: "Instructables", url: "https://www.instructables.com/member/{}", category: "development" },
  { name: "Intigriti", url: "https://app.intigriti.com/profile/{}", category: "other" },
  { name: "Ionic Forum", url: "https://forum.ionicframework.com/u/{}", category: "other" },
  { name: "Issuu", url: "https://issuu.com/{}", category: "other" },
  { name: "Itch.io", url: "https://{}.itch.io/", category: "gaming" },
  { name: "Jellyfin Weblate", url: "https://translate.jellyfin.org/user/{}/", category: "other" },
  { name: "Jimdo", url: "https://{}.jimdosite.com", category: "other" },
  { name: "Joplin Forum", url: "https://discourse.joplinapp.org/u/{}", category: "forum" },
  { name: "Kaggle", url: "https://www.kaggle.com/{}", category: "development" },
  { name: "Keybase", url: "https://keybase.io/{}", category: "security" },
  { name: "Kick", url: "https://kick.com/{}", category: "other" },
  { name: "Kongregate", url: "https://www.kongregate.com/accounts/{}", category: "gaming" },
  { name: "LOR", url: "https://www.linux.org.ru/people/{}/profile", category: "other" },
  { name: "Laracast", url: "https://laracasts.com/@{}", category: "other" },
  { name: "Launchpad", url: "https://launchpad.net/~{}", category: "development" },
  { name: "LeetCode", url: "https://leetcode.com/{}", category: "development" },
  { name: "Lichess", url: "https://lichess.org/@/{}", category: "gaming" },
  { name: "LinkedIn", url: "https://linkedin.com/in/{}", category: "social" },
  { name: "LinuxFR.org", url: "https://linuxfr.org/users/{}", category: "other" },
  { name: "LiveJournal", url: "https://{}.livejournal.com", category: "other" },
  { name: "Lobsters", url: "https://lobste.rs/u/{}", category: "tech" },
  { name: "LottieFiles", url: "https://lottiefiles.com/{}", category: "other" },
  { name: "LushStories", url: "https://www.lushstories.com/profile/{}", category: "other" },
  { name: "MMORPG Forum", url: "https://forums.mmorpg.com/profile/{}", category: "other" },
  { name: "Mamot", url: "https://mamot.fr/@{}", category: "other" },
  { name: "Memrise", url: "https://www.memrise.com/user/{}/", category: "other" },
  { name: "MixCloud", url: "https://www.mixcloud.com/{}/", category: "media" },
  { name: "Monkeytype", url: "https://monkeytype.com/profile/{}", category: "other" },
  { name: "Motorradfrage", url: "https://www.motorradfrage.net/nutzer/{}", category: "other" },
  { name: "MuseScore", url: "https://musescore.com/{}", category: "other" },
  { name: "MyAnimeList", url: "https://myanimelist.net/profile/{}", category: "media" },
  { name: "MyMiniFactory", url: "https://www.myminifactory.com/users/{}", category: "other" },
  { name: "Mydealz", url: "https://www.mydealz.de/profile/{}", category: "other" },
  { name: "Myspace", url: "https://myspace.com/{}", category: "other" },
  { name: "Naver", url: "https://blog.naver.com/{}", category: "regional" },
  { name: "Needrom", url: "https://www.needrom.com/author/{}/", category: "other" },
  { name: "Newgrounds", url: "https://{}.newgrounds.com", category: "gaming" },
  { name: "Nextcloud Forum", url: "https://help.nextcloud.com/u/{}/summary", category: "other" },
  { name: "Nightbot", url: "https://nightbot.tv/t/{}/commands", category: "other" },
  { name: "NintendoLife", url: "https://www.nintendolife.com/users/{}", category: "other" },
  { name: "NotABug.org", url: "https://notabug.org/{}", category: "other" },
  { name: "Nothing Community", url: "https://nothing.community/u/{}", category: "other" },
  { name: "Nyaa.si", url: "https://nyaa.si/user/{}", category: "other" },
  { name: "Open Collective", url: "https://opencollective.com/{}", category: "other" },
  { name: "OpenGameArt", url: "https://opengameart.org/users/{}", category: "other" },
  { name: "OpenStreetMap", url: "https://www.openstreetmap.org/user/{}", category: "other" },
  { name: "Opensource", url: "https://opensource.com/users/{}", category: "other" },
  { name: "Patreon", url: "https://www.patreon.com/{}", category: "finance" },
  { name: "PentesterLab", url: "https://pentesterlab.com/profile/{}", category: "other" },
  { name: "PepperNL", url: "https://nl.pepper.com/profile/{}", category: "other" },
  { name: "PepperPL", url: "https://www.pepper.pl/profile/{}", category: "other" },
  { name: "Pepperdeals", url: "https://www.pepperdeals.se/profile/{}", category: "other" },
  { name: "PepperealsUS", url: "https://www.pepperdeals.com/profile/{}", category: "other" },
  { name: "Periscope", url: "https://www.periscope.tv/{}/", category: "other" },
  { name: "Pinkbike", url: "https://www.pinkbike.com/u/{}/", category: "other" },
  { name: "Pinterest", url: "https://www.pinterest.com/{}/", category: "social" },
  { name: "Platzi", url: "https://platzi.com/p/{}/", category: "other" },
  { name: "PlayStore", url: "https://play.google.com/store/apps/developer?id={}", category: "other" },
  { name: "Playstrategy", url: "https://playstrategy.org/@/{}", category: "other" },
  { name: "Pokemon Showdown", url: "https://pokemonshowdown.com/users/{}", category: "other" },
  { name: "Polarsteps", url: "https://polarsteps.com/{}", category: "other" },
  { name: "Polygon", url: "https://www.polygon.com/users/{}", category: "other" },
  { name: "Pornhub", url: "https://pornhub.com/users/{}", category: "other" },
  { name: "Preisjaeger", url: "https://www.preisjaeger.at/profile/{}", category: "other" },
  { name: "ProductHunt", url: "https://www.producthunt.com/@{}", category: "tech" },
  { name: "PromoDJ", url: "http://promodj.com/{}", category: "other" },
  { name: "Promodescuentos", url: "https://www.promodescuentos.com/profile/{}", category: "other" },
  { name: "Pronouns.page", url: "https://pronouns.page/@{}", category: "other" },
  { name: "PyPi", url: "https://pypi.org/user/{}", category: "development" },
  { name: "Rajce.net", url: "https://{}.rajce.idnes.cz/", category: "other" },
  { name: "Rarible", url: "https://rarible.com/marketplace/api/v4/urls/{}", category: "other" },
  { name: "Rate Your Music", url: "https://rateyourmusic.com/~{}", category: "media" },
  { name: "Rclone Forum", url: "https://forum.rclone.org/u/{}", category: "other" },
  { name: "RedTube", url: "https://www.redtube.com/users/{}", category: "other" },
  { name: "Redbubble", url: "https://www.redbubble.com/people/{}", category: "other" },
  { name: "Reisefrage", url: "https://www.reisefrage.net/nutzer/{}", category: "other" },
  { name: "Replit.com", url: "https://replit.com/@{}", category: "development" },
  { name: "Roblox", url: "https://www.roblox.com/user.aspx?username={}", category: "social" },
  { name: "RoyalCams", url: "https://royalcams.com/profile/{}", category: "other" },
  { name: "RubyGems", url: "https://rubygems.org/profiles/{}", category: "development" },
  { name: "Rumble", url: "https://rumble.com/user/{}", category: "other" },
  { name: "SEOForum", url: "https://seoforum.com/@{}", category: "other" },
  { name: "SOOP", url: "https://www.sooplive.co.kr/station/{}", category: "other" },
  { name: "SWAPD", url: "https://swapd.co/u/{}", category: "other" },
  { name: "Sbazar.cz", url: "https://www.sbazar.cz/{}", category: "other" },
  { name: "Scratch", url: "https://scratch.mit.edu/users/{}", category: "other" },
  { name: "Shelf", url: "https://www.shelf.im/{}", category: "other" },
  { name: "ShitpostBot5000", url: "https://www.shitpostbot.com/user/{}", category: "other" },
  { name: "Sketchfab", url: "https://sketchfab.com/{}", category: "design" },
  { name: "Slack", url: "https://{}.slack.com", category: "other" },
  { name: "Slant", url: "https://www.slant.co/users/{}", category: "other" },
  { name: "Slides", url: "https://slides.com/{}", category: "other" },
  { name: "SmugMug", url: "https://{}.smugmug.com", category: "other" },
  { name: "Snapchat", url: "https://www.snapchat.com/add/{}", category: "social" },
  { name: "SoundCloud", url: "https://soundcloud.com/{}", category: "media" },
  { name: "SourceForge", url: "https://sourceforge.net/u/{}", category: "development" },
  { name: "SpeakerDeck", url: "https://speakerdeck.com/{}", category: "other" },
  { name: "Speedrun.com", url: "https://speedrun.com/users/{}", category: "gaming" },
  { name: "Spells8", url: "https://forum.spells8.com/u/{}", category: "other" },
  { name: "Splice", url: "https://splice.com/{}", category: "other" },
  { name: "Splits.io", url: "https://splits.io/users/{}", category: "other" },
  { name: "Sporcle", url: "https://www.sporcle.com/user/{}/people", category: "other" },
  { name: "Sportlerfrage", url: "https://www.sportlerfrage.net/nutzer/{}", category: "other" },
  { name: "SportsRU", url: "https://www.sports.ru/profile/{}/", category: "other" },
  { name: "Spotify", url: "https://open.spotify.com/user/{}", category: "media" },
  { name: "Strava", url: "https://www.strava.com/athletes/{}", category: "other" },
  { name: "SublimeForum", url: "https://forum.sublimetext.com/u/{}", category: "other" },
  { name: "TRAKTRAIN", url: "https://traktrain.com/{}", category: "media" },
  { name: "Tellonym.me", url: "https://tellonym.me/{}", category: "other" },
  { name: "Tenor", url: "https://tenor.com/users/{}", category: "other" },
  { name: "TheMovieDB", url: "https://www.themoviedb.org/u/{}", category: "other" },
  { name: "ThemeForest", url: "https://themeforest.net/user/{}", category: "other" },
  { name: "Tiendanube", url: "https://{}.mitiendanube.com/", category: "other" },
  { name: "TnAFlix", url: "https://www.tnaflix.com/profile/{}", category: "social" },
  { name: "Topcoder", url: "https://profiles.topcoder.com/{}/", category: "development" },
  { name: "Topmate", url: "https://topmate.io/{}", category: "other" },
  { name: "TradingView", url: "https://www.tradingview.com/u/{}/", category: "other" },
  { name: "Trakt", url: "https://www.trakt.tv/users/{}", category: "media" },
  { name: "TrashboxRU", url: "https://trashbox.ru/users/{}", category: "other" },
  { name: "Trawelling", url: "https://traewelling.de/@{}", category: "other" },
  { name: "Tuna", url: "https://tuna.voicemod.net/user/{}", category: "other" },
  { name: "Tweakers", url: "https://tweakers.net/gallery/{}", category: "other" },
  { name: "Ultimate-Guitar", url: "https://ultimate-guitar.com/u/{}", category: "other" },
  { name: "Unsplash", url: "https://unsplash.com/@{}", category: "design" },
  { name: "Untappd", url: "https://untappd.com/user/{}", category: "other" },
  { name: "VLR", url: "https://www.vlr.gg/user/{}", category: "other" },
  { name: "VSCO", url: "https://vsco.co/{}", category: "other" },
  { name: "Velog", url: "https://velog.io/@{}/posts", category: "other" },
  { name: "Vimeo", url: "https://vimeo.com/{}", category: "media" },
  { name: "VirusTotal", url: "https://www.virustotal.com/gui/user/{}", category: "other" },
  { name: "Vjudge", url: "https://VJudge.net/user/{}", category: "other" },
  { name: "WICG Forum", url: "https://discourse.wicg.io/u/{}/summary", category: "forum" },
  { name: "Wakatime", url: "https://wakatime.com/@{}", category: "development" },
  { name: "Warframe Market", url: "https://warframe.market/profile/{}", category: "other" },
  { name: "Warrior Forum", url: "https://www.warriorforum.com/members/{}.html", category: "other" },
  { name: "Wattpad", url: "https://www.wattpad.com/user/{}", category: "content" },
  { name: "WebNode", url: "https://{}.webnode.cz/", category: "other" },
  { name: "Weblate", url: "https://hosted.weblate.org/user/{}/", category: "other" },
  { name: "Weebly", url: "https://{}.weebly.com/", category: "other" },
  { name: "Windy", url: "https://community.windy.com/user/{}", category: "other" },
  { name: "Wix", url: "https://{}.wix.com", category: "social" },
  { name: "WolframalphaForum", url: "https://community.wolfram.com/web/{}/home", category: "other" },
  { name: "Wowhead", url: "https://wowhead.com/user={}", category: "other" },
  { name: "Wykop", url: "https://www.wykop.pl/ludzie/{}", category: "other" },
  { name: "Xbox Gamertag", url: "https://xboxgamertag.com/search/{}", category: "gaming" },
  { name: "Xvideos", url: "https://xvideos.com/profiles/{}", category: "other" },
  { name: "YouPic", url: "https://youpic.com/photographer/{}/", category: "other" },
  { name: "YouPorn", url: "https://youporn.com/uservids/{}", category: "other" },
  { name: "YouTube", url: "https://www.youtube.com/@{}", category: "media" },
  { name: "addons.wago.io", url: "https://addons.wago.io/user/{}", category: "other" },
  { name: "akniga", url: "https://akniga.org/profile/{}", category: "other" },
  { name: "authorSTREAM", url: "http://www.authorstream.com/{}/", category: "other" },
  { name: "couchsurfing", url: "https://www.couchsurfing.com/people/{}", category: "other" },
  { name: "d3RU", url: "https://d3.ru/user/{}/posts", category: "other" },
  { name: "datingRU", url: "http://dating.ru/{}", category: "other" },
  { name: "dcinside", url: "https://gallog.dcinside.com/{}", category: "other" },
  { name: "drive2", url: "https://www.drive2.ru/users/{}", category: "other" },
  { name: "eGPU", url: "https://egpu.io/forums/profile/{}/", category: "other" },
  { name: "exophase", url: "https://www.exophase.com/user/{}/", category: "other" },
  { name: "fixya", url: "https://www.fixya.com/users/{}", category: "other" },
  { name: "fl", url: "https://www.fl.ru/users/{}", category: "other" },
  { name: "freecodecamp", url: "https://www.freecodecamp.org/{}", category: "other" },
  { name: "geocaching", url: "https://www.geocaching.com/p/default.aspx?u={}", category: "other" },
  { name: "habr", url: "https://habr.com/ru/users/{}", category: "regional" },
  { name: "hackster", url: "https://www.hackster.io/{}", category: "development" },
  { name: "imood", url: "https://www.imood.com/users/{}", category: "other" },
  { name: "irecommend", url: "https://irecommend.ru/users/{}", category: "other" },
  { name: "jbzd.com.pl", url: "https://jbzd.com.pl/uzytkownik/{}", category: "other" },
  { name: "jeuxvideo", url: "https://www.jeuxvideo.com/profil/{}", category: "other" },
  { name: "kaskus", url: "https://www.kaskus.co.id/@{}", category: "other" },
  { name: "kwork", url: "https://kwork.ru/user/{}", category: "other" },
  { name: "last.fm", url: "https://last.fm/user/{}", category: "media" },
  { name: "leasehackr", url: "https://forum.leasehackr.com/u/{}/summary/", category: "other" },
  { name: "livelib", url: "https://www.livelib.ru/reader/{}", category: "other" },
  { name: "mastodon.cloud", url: "https://mastodon.cloud/@{}", category: "social" },
  { name: "mastodon.social", url: "https://mastodon.social/@{}", category: "social" },
  { name: "mastodon.xyz", url: "https://mastodon.xyz/@{}", category: "social" },
  { name: "mercadolivre", url: "https://www.mercadolivre.com.br/perfil/{}", category: "other" },
  { name: "moikrug", url: "https://moikrug.ru/{}", category: "other" },
  { name: "mstdn.io", url: "https://mstdn.io/@{}", category: "other" },
  { name: "mstdn.social", url: "https://mstdn.social/@{}", category: "other" },
  { name: "n8n Community", url: "https://community.n8n.io/u/{}/summary", category: "other" },
  { name: "nairaland.com", url: "https://www.nairaland.com/{}", category: "other" },
  { name: "namuwiki", url: "https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:{}", category: "other" },
  { name: "nnRU", url: "https://{}.www.nn.ru/", category: "other" },
  { name: "note", url: "https://note.com/{}", category: "regional" },
  { name: "npm", url: "https://www.npmjs.com/~{}", category: "development" },
  { name: "osu!", url: "https://osu.ppy.sh/users/{}", category: "gaming" },
  { name: "pikabu", url: "https://pikabu.ru/@{}", category: "regional" },
  { name: "pixelfed.social", url: "https://pixelfed.social/{}/", category: "social" },
  { name: "pr0gramm", url: "https://pr0gramm.com/user/{}", category: "other" },
  { name: "satsisRU", url: "https://satsis.info/user/{}", category: "other" },
  { name: "sessionize", url: "https://sessionize.com/{}", category: "other" },
  { name: "social.tchncs.de", url: "https://social.tchncs.de/@{}", category: "other" },
  { name: "spletnik", url: "https://spletnik.ru/user/{}", category: "other" },
  { name: "svidbook", url: "https://www.svidbook.ru/user/{}", category: "social" },
  { name: "tistory", url: "https://{}.tistory.com/", category: "other" },
  { name: "toster", url: "https://www.toster.ru/user/{}/answers", category: "other" },
  { name: "tumblr", url: "https://{}.tumblr.com/", category: "social" },
  { name: "uid", url: "http://uid.me/{}", category: "other" },
  { name: "write.as", url: "https://write.as/{}", category: "other" },
  { name: "xHamster", url: "https://xhamster.com/users/{}", category: "other" },
  { name: "znanylekarz.pl", url: "https://www.znanylekarz.pl/{}", category: "other" },
];

// Batch size for parallel checks — keeps total scan under 2 minutes
const BATCH_SIZE = 15;

module.exports = {
  name: "username-enum",
  profileTypes: ["username"],

  async scan(profile, rateLimiter) {
    const username = profile.value;
    const findings = [];

    const checkPlatform = async (platform) => {
      const release = await rateLimiter.acquire();
      try {
        const profileUrl = platform.url.replace("{}", username);
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 8000);

        try {
          const res = await fetch(profileUrl, {
            method: "HEAD",
            signal: controller.signal,
            headers: { "User-Agent": "Mozilla/5.0 (compatible; OSINT-Scanner/1.0)" },
            redirect: "manual",
          });
          clearTimeout(timeout);

          // 200 = account exists, 3xx redirect to profile = exists
          if (res.status === 200 || (res.status >= 300 && res.status < 400)) {
            return {
              category: "account_found",
              severity: "medium",
              title: `Account found on ${platform.name}`,
              description: `Username "${username}" has an active profile on ${platform.name}. This publicly associates this username with the platform.`,
              sourceUrl: profileUrl,
              rawData: { platform: platform.name, status: res.status, category: platform.category },
              remediation: `Review your ${platform.name} profile privacy settings. Consider removing or anonymizing the account if it's not needed.`,
            };
          }
        } catch (err) {
          clearTimeout(timeout);
          // Timeout or network error — skip silently
        }
        return null;
      } finally {
        release();
      }
    };

    // Run in batches to avoid overwhelming the rate limiter
    for (let i = 0; i < PLATFORMS.length; i += BATCH_SIZE) {
      const batch = PLATFORMS.slice(i, i + BATCH_SIZE);
      const results = await Promise.all(batch.map(checkPlatform));
      for (const result of results) {
        if (result) findings.push(result);
      }
    }

    // If no accounts found, add info-level finding
    if (findings.length === 0) {
      findings.push({
        category: "account_found",
        severity: "info",
        title: "No accounts found across checked platforms",
        description: `Username "${username}" was not found on any of the ${PLATFORMS.length} platforms checked. This is a good sign for username privacy.`,
        rawData: { platformsChecked: PLATFORMS.length },
        remediation: null,
      });
    }

    return findings;
  },
};
